services:
  db:
    image: mariadb:10.6
    restart: always
    environment:
      MYSQL_DATABASE: hotelserenity
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "3306:3306"

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DJANGO_SETTINGS_MODULE=myproject.settings
      - DB_HOST=db
      - DB_NAME=hotelserenity
      - DB_USER=user
      - DB_PASS=password
