# Generated by Django 5.0.7 on 2024-12-10 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicios',
            name='imagenes',
        ),
        migrations.AddField(
            model_name='servicios',
            name='imagen',
            field=models.ImageField(default=1, upload_to='servicios/'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='ImagenServicio',
        ),
    ]
