# Generated by Django 5.0.7 on 2024-12-10 07:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_remove_servicios_imagenes_servicios_imagen_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pabellon',
            options={},
        ),
        migrations.RemoveField(
            model_name='habitacion',
            name='imagenes',
        ),
        migrations.RemoveField(
            model_name='pabellon',
            name='imagenes',
        ),
        migrations.AddField(
            model_name='habitacion',
            name='imagen',
            field=models.ImageField(default=1, upload_to='habitaciones/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='imagenhabitacion',
            name='habitacion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='habitaciones', to='myapp.habitacion'),
        ),
        migrations.AddField(
            model_name='imagenpabellon',
            name='pabellon',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='myapp.pabellon'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pabellon',
            name='imagen',
            field=models.ImageField(default=1, upload_to='pabellones/'),
            preserve_default=False,
        ),
    ]
