# Generated by Django 5.0.7 on 2025-01-07 16:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_pabellon_options_remove_habitacion_imagenes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagenhabitacion',
            name='habitacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='habitaciones', to='myapp.habitacion'),
        ),
    ]
